config/routes.rb
Rails.application.routes.draw do
  resources :users
  root "users#login"
  resources :users do
    collection do
      post :auth
    end

    member do
      get  :read
    end

    resources :posts
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
  default_scope { order(published_at: :desc) }

  before_create do
    self.published_at = DateTime.now
  end

  belongs_to :author, :class_name => :User, :foreign_key => :author_id
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true

  has_many :posts, :foreign_key => 'author_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_author, only: [:index, :new, :show, :create, :edit, :update, :destroy]
  before_action :set_post, only: [:show, :read, :edit, :update, :destroy]

  # Views API
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def show
  end

  def edit
  end

  # CRUD API
  def create
    @post = Post.new(post_params)
    @post.author = @author

    if @post.save
      render json: {
        :message => 'Post succesfully created',
        :post_id => @post.id
      }, status: :ok
    else
      render json: {
        :message => 'Failed to create new post',
        :details => @post.errors
      }, status: :unprocessable_entity
    end
  end

  def read
    render json: @post
  end

  def update
    if @post.update(post_params)
      render json: {
        :message => 'Post was successfully updated.'
      }, :status => :ok
    else
      render json: {
        :message => "Failed to update post (ID: #{params[:id]})",
        :details => @post.errors
      }, status: :unprocessable_entity
    end
  end

  def destroy
    if @post.present?
      @post.destroy
      head :no_content
    else
      render json: {
        :message => 'Post does not longer exists',
        :details => nil
      }, status: :not_found
    end
  end

  private
    def set_author
      @author = User.find(params[:user_id])
    end

    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :content, :author_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :read, :edit, :update, :destroy]
  before_action :authorize, only: [:auth]

  # Views API
  def index
    @users = User.all
    render json: @users
  end

  def new
    @user = User.new
  end

  def show
    @posts = @user.posts
  end

  def edit
  end

  def login
  end

  # CRUD API
  def create
    name         = user_params[:name]
    email        = user_params[:email]
    avatar_image = user_params[:avatar_image]

    if avatar_image.present?
      extension = File.extname avatar_image.original_filename
      file_url  = "uploads/#{SecureRandom.uuid}#{extension}"
      file_path = Rails.root.join 'public', file_url

      File.open(file_path, 'wb') do |file|
        file.write(avatar_image.read)
      end

      avatar_image = file_url
    end

    @user = User.new(name: name, email: email, avatar_image: avatar_image)

    if @user.save
      render json: {
        :message => 'User succesfully created',
        :user_id => @user.id
      }, status: :ok
    else
      render json: {
        :message => 'Failed to create new user',
        :details => @user.errors
      }, status: :unprocessable_entity
    end
  end

  def read
    if @user.present?
      render json: @user
    else
      render json: {
        :message => 'User not found',
        :details => ''
      }, status: :not_found
    end
  end

  def update
    name         = user_params[:name]
    email        = user_params[:email]
    avatar_image = user_params[:avatar_image]

    if avatar_image.present?
      extension = File.extname avatar_image.original_filename
      file_url  = "uploads/#{SecureRandom.uuid}#{extension}"
      file_path = Rails.root.join('public', file_url)

      File.open(file_path, 'wb') do |file|
        file.write(avatar_image.read)
      end

      avatar_image = file_url

      # Delete previous avatar from disk
      if @user.avatar_image.present?
        old_avatar_path = Rails.root.join 'public', @user.avatar_image

        if File.exists? old_avatar_path
          File.delete old_avatar_path
        end
      end
    end

    if @user.update(name: name, email: email, avatar_image: avatar_image)
      render json: {
        :message => 'User was successfully updated.'
      }, :status => :ok
    else
      render json: {
        :message => "Failed to update user (ID: #{params[:id]})",
        :details => @user.errors
      }, status: :unprocessable_entity
    end
  end

  def destroy
    if @user.present?
      @user.destroy
      head :no_content
    else
      render json: {
        :message => 'User does not longer exists',
        :details => nil
      }, status: :not_found
    end
  end

  # Just check if the user exists
  def auth
    if @user.present?
      redirect_to :action => 'show', :id => @user.id
    else
      redirect_to root_path, flash: { :error => "User not found" }
    end
  end

  private
    # Dummy authorization middleware
    def authorize
      @user = User.find_by_email(user_params[:email])
    end

    def set_user
      @user = User.find_by_id(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email, :avatar_image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_edit_form.html.erb
<%= form_with(model: [@author, @post], local: true, :html => {:class => "form"}) do |form| %>
  <div id="error_explanation" style="display: none">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

    <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>

  <div class="actions">
    <label for="title"> Title </label>
    <%= form.text_field :title %>
    <br />
    <label for="content"> Content </label>
    <%= form.text_area :content %>
    <br />
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_form.html.erb
<%= form_with(model: [@author, @post], local: true, :html => {:class => "form"}) do |form| %>
  <div id="error_explanation" style="display: none">
    <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

    <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>

  <div class="actions">
    <label for="title"> Title </label>
    <input id="title" name="post[title]" placeholder="Enter your post title here" />
    <br />
    <label for="content"> Content </label>
    <textarea id="name" name="post[content]"> </textarea>
    <br />
    <input type="button" id="send" value="Create Post" />
  </div>
<% end %>

<!-- Creating Post with AJAX -->
<script type="text/javascript">
  var url;

  <% if request.url.include?('new') %>
  url = '/users/<%= @author.id %>/posts';
  <% else %>
  url = '/users/<%= @author.id %>/posts/<%= @post.id %>';
  <% end %>

  var onPageLoad = function (event) {
    var form, button;

    form   = document.querySelector('.form');
    button = document.querySelector("#send");

    button.addEventListener('click', function (event) {
      var ajax = new XMLHttpRequest();

      ajax.open('POST', url, true);
      ajax.addEventListener('readystatechange', function (event) {
        if (ajax.readyState === 4 && ajax.status === 200) {
          var data = JSON.parse(ajax.responseText);

          alert(data.message);
          window.location = window.location.href.replace(/\/new/gi, '');
        }
      });
      ajax.send(new FormData(form));
    });

    document.removeEventListener('turbolinks:load', onPageLoad);
  };

  document.addEventListener('turbolinks:load', onPageLoad, { once: true });
</script>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'edit_form', post: @post %>

<%= link_to 'Show', user_post_path(@author, @post) %> |
<%= link_to 'Back', user_posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %> </td>
        <td><%= link_to 'Show', user_post_path(@author, post) %></td>
        <td><%= link_to 'Edit', edit_user_post_path(@author, post) %></td>
        <td><%= link_to 'Destroy', [@author, post], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_user_post_path(@author) %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', user_posts_path(@author) %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_post_path(@post) %> |
<%= link_to 'Back', user_posts_path %>

<h1> <%= @post.title %> </h1>
<div> <%= @post.content %> </div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= label_tag :name, 'Full name' %>
    <%= form.text_field :name, { placeholder: 'Enter your full name here' } %>
    <br />
    <%= label_tag :email, 'E-mail' %>
    <%= form.email_field :email %>
    <br />
    <%= label_tag :avatar, 'Avatar' %>
    <%= form.file_field :avatar_image %>
    </br>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/login.html.erb
<% flash.each do |name, msg| -%>
    <%= content_tag :div, msg, class: name %>
<% end -%>

<%= form_with(scope: :user, url: auth_users_path) do |form| %>
  <%= label_tag :email, 'Enter your email' %>
  <%= form.text_field :email %>
  <%= form.submit 'Login' %>
  <%= link_to 'Sign up', new_user_path %>
<% end %>

<style type="text/css">
  .error {
    color: red;
  }
</style>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit your user', edit_user_path(@user) %> |
<%= link_to 'Your posts', user_posts_path(@user) %> |
<%= link_to 'Back', users_path %>

<br />
<% if @user.avatar_image %>
  <img src="/<%= @user.avatar_image %>" width="64" height="64" />
<% end %>
<p> <%= @user.name %> </p>
<p> <%= @user.email %> </p>